[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./requirements.txt"

[build.environment]
  NODE_VERSION = "18.x"
  NPM_FLAGS = "--no-audit --no-fund"
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/api/*"
  to = "https://your-api-domain.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[build.processing.html]
  pretty_urls = true
